name: BambooHR with Puppeteer
on:
  pull_request:
    types: ['labeled']
  push:
    branches:
      - "test-*"
  schedule:
    - cron: '0 8 * * 1-5'
jobs:
  puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn
      - name: Run Puppeteer
        uses: ianwalter/puppeteer@v2.0.0
        env:
            COMPANY: ${{ secrets.COMPANY_BAMBOOHR }}
            USER: ${{ secrets.USER_BAMBOOHR }}
            PASSWORD: ${{ secrets.PASSWORD_BAMBOOHR }}
        with:
          args: yarn run start
