name: cURL BambooHR API
on:
  push:
  schedule:
    - cron: '0 0 5 31 2 ?'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: enflo/curl-action@master
      with:
        curl: https://${{secrets.BAMBOOHR_API_KEY}}:x@api.bamboohr.com/api/gateway.php/${{secrets.COMPANY_BAMBOOHR}}/v1/timetracking/record/123456
